-- Active: 1754239607830@@127.0.0.1@3306@test_db

CREATE DATABASE IF NOT EXISTS `test_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `test_db`;

CREATE TABLE IF NOT EXISTS `people` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `age` TINYINT UNSIGNED NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB;
